services:
    app:
        build: .
        command: npm start
        image: app2
        restart: on-failure
        depends_on:
            - banco
        ports:
            - 5000:5000

    banco:
      restart: always
      ports: 
            - 3306:3306
      image: mariadb:10.9
      environment:
        MYSQL_DATABASE: appdocker
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_PASSWORD: admin
